/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates.

 * and open the template in the editor.
 */
package bismillahproject;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
/**
 *
 * @author Indri
 */
public class Home extends javax.swing.JFrame {
        String pilihan = "";
        String perawatan ="";
        String sistempembayaran;
        int Harga_makananKucing;
        int Harga_makananAnjing;
        int Harga_perawatan;
        int Bayar, Beli, Harga;
        int Bayar1,Beli1,Harga1;
        int Jumlah_Harga;
        int totalbelanja;
        int Kembalian;
        int ongkir;
        int FixTotal;
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        jLabel2.setText(Register.name); // Buat Masukkin nama kita Otomatis setelah Login
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TotalSemua = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboPilihan1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtHarga1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtBeli1 = new javax.swing.JTextField();
        btnTambah1 = new javax.swing.JButton();
        txtTotal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboPilihan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBeli = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hargaperawatan = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Grooming = new javax.swing.JCheckBox();
        spa = new javax.swing.JCheckBox();
        Scalling = new javax.swing.JCheckBox();
        Styling = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShop = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ongkoskirim = new javax.swing.JTextField();
        chkDebit = new javax.swing.JCheckBox();
        chkCOD = new javax.swing.JCheckBox();
        btnPrint = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btncheckout = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jMenu1.setText("jMenu1");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(124, 58, 67));
        jLabel1.setText("HAPPY SHOPPING,");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 127, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(124, 58, 67));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 134, -1, -1));

        btnClear.setBackground(new java.awt.Color(244, 245, 240));
        btnClear.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 544, 90, 35));

        jPanel1.setBackground(new java.awt.Color(244, 245, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 0, 16))); // NOI18N

        TotalSemua.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        TotalSemua.setText("0");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        jLabel11.setText("Rp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addComponent(TotalSemua, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 43, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indri\\Desktop\\ferree.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 97));

        Exit.setBackground(new java.awt.Color(244, 245, 240));
        Exit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 585, 70, 35));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(124, 58, 67));
        jLabel8.setText("Makanan Anjing");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 299, -1, -1));

        ComboPilihan1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        ComboPilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silakan Pilih", "Pedigree Puppy 480 gr", "Pedigree Adult Beef 1kg", "Proplan Dog Formula 1kg", "Proplan Chicken & Rice 1kg", "Royal Canin Baby 3kg", "Eukanubah Small Breed 1.5kg", "Science Diet Small Bites 1kg" }));
        ComboPilihan1.setMinimumSize(new java.awt.Dimension(80, 28));
        ComboPilihan1.setPreferredSize(new java.awt.Dimension(80, 28));
        ComboPilihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPilihan1ActionPerformed(evt);
            }
        });
        getContentPane().add(ComboPilihan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 294, 207, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(124, 58, 67));
        jLabel9.setText("Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 299, -1, -1));

        txtHarga1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        txtHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHarga1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 295, 120, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(124, 58, 67));
        jLabel10.setText("Jumlah");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 299, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(124, 58, 67));
        jLabel12.setText("Total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 299, -1, -1));

        txtBeli1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        txtBeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBeli1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 295, 40, -1));

        btnTambah1.setBackground(new java.awt.Color(244, 245, 240));
        btnTambah1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        btnTambah1.setForeground(new java.awt.Color(146, 208, 80));
        btnTambah1.setText("Tambah");
        btnTambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambah1MouseClicked(evt);
            }
        });
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 291, 100, 35));

        txtTotal1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        txtTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotal1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 295, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 58, 67));
        jLabel3.setText("Makanan Kucing");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 247, -1, -1));

        ComboPilihan.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        ComboPilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silakan Pilih", "Whiskas Ocean Fish 480 gr", "Whiskas Kaleng Tuna 400 gr", "Whiskas Dry Mackarel 1.2kg", "Whiskas Pouch Junior 85gr", "Royal Canin Kitten 400 gr", "Me-O adult 1.5 kg", "Pro Plan Tract 3.18kg" }));
        ComboPilihan.setMinimumSize(new java.awt.Dimension(80, 28));
        ComboPilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPilihanActionPerformed(evt);
            }
        });
        getContentPane().add(ComboPilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 242, 207, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(124, 58, 67));
        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 243, -1, 26));

        txtHarga.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 243, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(124, 58, 67));
        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 247, -1, -1));

        txtBeli.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        txtBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 243, 40, -1));

        btnTambah.setBackground(new java.awt.Color(244, 245, 240));
        btnTambah.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(146, 208, 80));
        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 239, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(124, 58, 67));
        jLabel6.setText("Total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 241, -1, 31));

        txtTotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 243, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(124, 58, 67));
        jLabel13.setText("Perawatan Hewan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 364, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(124, 58, 67));
        jLabel14.setText("Harga");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 364, -1, -1));

        hargaperawatan.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        getContentPane().add(hargaperawatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 360, 170, -1));

        jButton3.setBackground(new java.awt.Color(244, 245, 240));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(146, 208, 80));
        jButton3.setText("Tambah");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 356, 100, 35));

        Grooming.setBackground(new java.awt.Color(244, 245, 240));
        Grooming.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        Grooming.setForeground(new java.awt.Color(124, 58, 67));
        Grooming.setText("Grooming Service");
        Grooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroomingActionPerformed(evt);
            }
        });
        getContentPane().add(Grooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 361, -1, -1));

        spa.setBackground(new java.awt.Color(244, 245, 240));
        spa.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        spa.setForeground(new java.awt.Color(124, 58, 67));
        spa.setText("SPA");
        spa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaActionPerformed(evt);
            }
        });
        getContentPane().add(spa, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 361, -1, -1));

        Scalling.setBackground(new java.awt.Color(244, 245, 240));
        Scalling.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        Scalling.setForeground(new java.awt.Color(124, 58, 67));
        Scalling.setText("Scalling");
        Scalling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScallingActionPerformed(evt);
            }
        });
        getContentPane().add(Scalling, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 361, -1, -1));

        Styling.setBackground(new java.awt.Color(244, 245, 240));
        Styling.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        Styling.setForeground(new java.awt.Color(124, 58, 67));
        Styling.setText("Styling");
        Styling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StylingActionPerformed(evt);
            }
        });
        getContentPane().add(Styling, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 361, -1, -1));

        tblShop.setBackground(new java.awt.Color(235, 236, 231));
        tblShop.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblShop.setForeground(new java.awt.Color(0, 0, 0));
        tblShop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga", "Jumlah", "Total"
            }
        ));
        tblShop.setGridColor(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(tblShop);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 423, 964, 109));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(124, 58, 67));
        jLabel15.setText("Sistem Pembayaran");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 552, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(124, 58, 67));
        jLabel16.setText("Ongkir");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 628, -1, -1));

        ongkoskirim.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        ongkoskirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ongkoskirimActionPerformed(evt);
            }
        });
        getContentPane().add(ongkoskirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 620, 74, -1));

        chkDebit.setBackground(new java.awt.Color(244, 245, 240));
        chkDebit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        chkDebit.setForeground(new java.awt.Color(124, 58, 67));
        chkDebit.setText("DEBIT");
        chkDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDebitActionPerformed(evt);
            }
        });
        getContentPane().add(chkDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 549, -1, -1));

        chkCOD.setBackground(new java.awt.Color(244, 245, 240));
        chkCOD.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        chkCOD.setForeground(new java.awt.Color(124, 58, 67));
        chkCOD.setText("Cash On Delivery");
        chkCOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCODActionPerformed(evt);
            }
        });
        getContentPane().add(chkCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 585, -1, -1));

        btnPrint.setBackground(new java.awt.Color(244, 245, 240));
        btnPrint.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
        });
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 544, 90, 35));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(124, 58, 67));
        jLabel20.setText("Alamat");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 181, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(124, 58, 67));
        jLabel21.setText("No.Telp");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 181, -1, -1));

        btncheckout.setBackground(new java.awt.Color(244, 245, 240));
        btncheckout.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        btncheckout.setForeground(new java.awt.Color(146, 208, 80));
        btncheckout.setText("Checkout");
        btncheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncheckoutMouseClicked(evt);
            }
        });
        btncheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 544, 90, 35));

        jTextField3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 177, 171, -1));

        jTextField4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 177, 146, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public void TotalinSemua(){
      
            DefaultTableModel dataModel = (DefaultTableModel) tblShop.getModel();
                int total = 0;
                for (int i = 0; i<tblShop.getRowCount();i++){
                    int amount = Integer.parseInt((String)tblShop.getValueAt(i,3));
                    total += amount;
            // (i,3) maksudnya totalin Tabel yang posisinya sebagai Index Ketiga yaitu kolom total
 
                }
                    TotalSemua.setText(""+total); //Untuk menampilkan total di textfield atas
                    FixTotal = total + 15000; // Untuk Notalin Ongkir
                    
                    {
                        if(chkDebit.isSelected())
                            {
                            TotalSemua.setText(""+FixTotal);  
                            }
                        else if (chkCOD.isSelected())
                            {
                                TotalSemua.setText(""+FixTotal);
                            }   
                    }                  
        }               
                      
    private void txtBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeliActionPerformed

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
        // Mengalikan Total Belanjaan
        
        
        DefaultTableModel dataModel = (DefaultTableModel)tblShop.getModel();
            Harga = Integer.parseInt(txtHarga.getText());
            Beli = Integer.parseInt(txtBeli.getText());
            
            Bayar = Harga * Beli;
            
        // untuk nampilin di Field Total
            txtTotal.setText(""+Integer.toString(Bayar));
       

            
//--------------------------------Untuk memasukkan/menambahkan data ke dalam Table-----------------------------------//
        //Default Tabel Model adalah class yang digunakan untuk membuat permodelan pada tabel, jadi nanti tabelnya akan
        //bertambah sesuai pesanan kita
        //Daftar List semua data disimpannya dalam array
            
            List list = new ArrayList <>();
            tblShop.setAutoCreateColumnsFromModel(true);
                list.add(ComboPilihan.getSelectedItem());
                list.add(txtHarga.getText());
                list.add(txtBeli.getText());
                list.add(txtTotal.getText());
            dataModel.addRow(list.toArray());
            TotalinSemua();
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHarga1ActionPerformed

    private void btnTambah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel)tblShop.getModel();
            Harga1 = Integer.parseInt(txtHarga1.getText());
            Beli1 = Integer.parseInt(txtBeli1.getText());
            
            Bayar1 = Harga1 * Beli1;
            
        //Untuk nampilin di field Total    
            txtTotal1.setText(""+Integer.toString(Bayar1));
            
            
//--------------------------------Untuk memasukkan/menambahkan data ke dalam Table-----------------------------------//
        // Default Table Model adalah class yang digunakan untuk membuat permodelan pada tabel, Kaya nambahin kolom/baris
        // daftar List semua data disimpannya dalam array
            
            List list = new ArrayList <>();
            tblShop.setAutoCreateColumnsFromModel(true);
                list.add(ComboPilihan1.getSelectedItem());
                list.add(txtHarga1.getText());
                list.add(txtBeli1.getText());
                list.add(txtTotal1.getText());
            dataModel.addRow(list.toArray());
            TotalinSemua();
    }//GEN-LAST:event_btnTambah1MouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        
        // Untuk mengahapus semua data yang ada di table
        //pada kondisi if,data di dalam tabel dihitung mengggunakan fungsi getRowCount() jika Hasilnya >0 maka Akan dilakukan penghapusan data
        
        DefaultTableModel dataModel = (DefaultTableModel) tblShop.getModel();
        if(tblShop.getRowCount()>0){
                for (int i = tblShop.getRowCount()-1;i>-1;i--){
                    dataModel.removeRow(i);
                    txtBeli.setText("");
                    txtTotal.setText("");
                    txtHarga.setText("");
                    txtBeli1.setText("");
                    txtTotal1.setText("");
                    txtHarga1.setText("");
                    TotalSemua.setText("");
                    hargaperawatan.setText("");
                    ongkoskirim.setText("");
                }
        }
    }//GEN-LAST:event_btnClearMouseClicked

    private void ComboPilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPilihanActionPerformed
        // TODO add your handling code here:
        pilihan = (String) ComboPilihan.getSelectedItem();
            switch (pilihan){
                case "Whiskas Ocean Fish 480 gr" :
                    Harga_makananKucing = 32000 ;
                  break;
                case "Whiskas Kaleng Tuna 400 gr" :
                    Harga_makananKucing = 45000 ;
                  break;
                case "Whiskas Dry Mackarel 1.2kg" :
                    Harga_makananKucing = 70500 ;
                  break;
                case "Whiskas Pouch Junior 85gr" :
                    Harga_makananKucing = 80000 ;
                  break;
                case "Royal Canin Kitten 400 gr" :
                    Harga_makananKucing = 55000 ;
                  break;
                case "Me-O adult 1.5 kg" :
                    Harga_makananKucing = 68000 ;
                  break;
                case "Pro Plan Tract 3.18kg" :
                    Harga_makananKucing = 325000 ;
                  break;
                
                //case "Silver" :
                //Harga_makananKucing = 35000;
                //break;
                //case"Gold":
                //Harga_makananKucing = 55000;
                //break;
                //case"Diamond":
                //Harga_makananKucing = 115000;
                //break;                       
            }
            
        // untuk nampilin di field Harga
        txtHarga.setText("" + Integer.toString(Harga_makananKucing));
        
    }//GEN-LAST:event_ComboPilihanActionPerformed

    private void ComboPilihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPilihan1ActionPerformed
        // TODO add your handling code here:
        pilihan = (String)ComboPilihan1.getSelectedItem();
            switch (pilihan){
                case "Pedigree Puppy 480 gr" :
                    Harga_makananAnjing = 35000;
                  break;
                case "Pedigree Adult Beef 1kg" :
                    Harga_makananAnjing = 42000;
                break;
                case "Proplan Dog Formula 1kg" :
                    Harga_makananAnjing = 55000;
                  break;
                case "Proplan Chicken & Rice 1kg" :
                    Harga_makananAnjing = 68000;
                  break;
                case "Royal Canin Baby 3kg" :
                    Harga_makananAnjing = 300000;
                  break;
                case "Eukanubah Small Breed 1.5kg" :
                    Harga_makananAnjing = 87000;
                  break;  
                case "Science Diet Small Bites 1kg" :
                    Harga_makananAnjing = 137000;
                  break;
                
                  
                //case "Silver" :
                //Harga_makananAnjing = 38000;
                //break;
                //case "Gold" :
                //Harga_makananAnjing = 60000;
                //break;
                //case "Diamond" :
                //Harga_makananAnjing = 125000;
                //break; 
            }
        
        // untuk nampilin di field Harga
            txtHarga1.setText("" + Integer.toString(Harga_makananAnjing));
    }//GEN-LAST:event_ComboPilihan1ActionPerformed

    private void txtTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal1ActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void txtBeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeli1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void GroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroomingActionPerformed
        // TODO add your handling code here:
            perawatan = "Grooming";
            Harga_perawatan = 105000;
            
        //Supaya hanya bisa memilih satu dan untuk memudahkan USER, supaya gampang melihat Harga, jadi yang tertampil hanya yang diklik
               Scalling.setSelected(false);
               spa.setSelected(false);
               Styling.setSelected(false);

            hargaperawatan.setText("" + Integer.toString(Harga_perawatan));

    }//GEN-LAST:event_GroomingActionPerformed

    private void spaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaActionPerformed
        // TODO add your handling code here:
            perawatan = "Spa";
            Harga_perawatan = 90000;
        
        //Supaya hanya bisa memilih satu dan untuk memudahkan USER, supaya gampang melihat Harga, jadi yang tertampil hanya yang diklik
                Scalling.setSelected(false);
                Styling.setSelected(false);
                Grooming.setSelected(false);

            hargaperawatan.setText("" + Integer.toString(Harga_perawatan));
    }//GEN-LAST:event_spaActionPerformed

    private void ScallingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScallingActionPerformed
        // TODO add your handling code here:
            perawatan = "Scalling";
            Harga_perawatan = 75000;

        //Supaya hanya bisa memilih satu dan untuk memudahkan USER, supaya gampang melihat Harga, jadi yang tertampil hanya yang diklik    
                spa.setSelected(false);
                Styling.setSelected(false);
                Grooming.setSelected(false);

            hargaperawatan.setText("" + Integer.toString(Harga_perawatan));
        
    }//GEN-LAST:event_ScallingActionPerformed

    private void StylingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StylingActionPerformed
        // TODO add your handling code here:
            perawatan = "Styling";
            Harga_perawatan = 100000;
        
        //Supaya hanya bisa memilih satu dan untuk memudahkan USER, supaya gampang melihat Harga, jadi yang tertampil hanya yang diklik
                Scalling.setSelected(false);
                spa.setSelected(false);
                Grooming.setSelected(false);

            hargaperawatan.setText("" + Integer.toString(Harga_perawatan));
    }//GEN-LAST:event_StylingActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
       
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
       
        // Untuk memasukkan/menambahkan data ke Table
        // Default Table Model adalah class yang digunakan untuk membuat permodelan pada tabel, Kaya nambahin kolom/baris
        // daftar List semua data disimpannya dalam array
          
            
        DefaultTableModel dataModel = (DefaultTableModel)tblShop.getModel();
            List list = new ArrayList <>();
            tblShop.setAutoCreateColumnsFromModel(true);
            list.add(perawatan);
            list.add(hargaperawatan.getText());
            list.add("-");
            list.add(hargaperawatan.getText());
            dataModel.addRow(list.toArray());
            TotalinSemua();
    }//GEN-LAST:event_jButton3MouseClicked

    private void chkDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDebitActionPerformed
        // TODO add your handling code here:
        sistempembayaran = "Debit";
        ongkir  = 15000;
        
        chkCOD.setSelected(false);
        
        ongkoskirim.setText("" + Integer.toString(ongkir));
        TotalinSemua();
        
    }//GEN-LAST:event_chkDebitActionPerformed

    private void chkCODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCODActionPerformed
        // TODO add your handling code here:
        sistempembayaran = "COD";
        ongkir  = 15000;
        
        chkDebit.setSelected(false);
        
        ongkoskirim.setText("" + Integer.toString(ongkir));
        TotalinSemua();
    }//GEN-LAST:event_chkCODActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
                       
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        // TODO add your handling code here:
        try {
                tblShop.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btncheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncheckoutActionPerformed

    private void ongkoskirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ongkoskirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ongkoskirimActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btncheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncheckoutMouseClicked
        // TODO add your handling code here:
        
        // Untuk mengahapus semua data yang ada di table
        //pada kondisi if,data di dalam tabel dihitung mengggunakan fungsi getRowCount() jika Hasilnya >0 maka Akan dilakukan penghapusan data
        
        DefaultTableModel dataModel = (DefaultTableModel) tblShop.getModel();
        if(tblShop.getRowCount()>0){
                for (int i = tblShop.getRowCount()-1;i>-1;i--){
                    dataModel.removeRow(i);
                    txtBeli.setText("");
                    txtTotal.setText("");
                    txtHarga.setText("");
                    txtBeli1.setText("");
                    txtTotal1.setText("");
                    txtHarga1.setText("");
                    TotalSemua.setText("");
                    hargaperawatan.setText("");
                    ongkoskirim.setText("");
                }
        }
        
        JOptionPane.showMessageDialog(null, "Terimakasih, Pesanan Anda Akan Segera Diantar");
               
    }//GEN-LAST:event_btncheckoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboPilihan;
    private javax.swing.JComboBox<String> ComboPilihan1;
    private javax.swing.JButton Exit;
    private javax.swing.JCheckBox Grooming;
    private javax.swing.JCheckBox Scalling;
    private javax.swing.JCheckBox Styling;
    private javax.swing.JLabel TotalSemua;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JButton btncheckout;
    private javax.swing.JCheckBox chkCOD;
    private javax.swing.JCheckBox chkDebit;
    private javax.swing.JTextField hargaperawatan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField ongkoskirim;
    private javax.swing.JCheckBox spa;
    private javax.swing.JTable tblShop;
    private javax.swing.JTextField txtBeli;
    private javax.swing.JTextField txtBeli1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHarga1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal1;
    // End of variables declaration//GEN-END:variables
}
